apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: watchdog-external-secret
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "terminus-watchdog.labels" . | nindent 4 }}
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: watchdog-secrets
    creationPolicy: Owner
  data:
    - secretKey: ARGOCD_TOKEN
      remoteRef:
        key: {{ .Values.vault.secretBasePath }}/argocd-token
        property: ARGOCD_TOKEN
    - secretKey: DISCORD_BOT_TOKEN
      remoteRef:
        key: {{ .Values.vault.secretBasePath }}/discord-bot-token
        property: DISCORD_BOT_TOKEN
    - secretKey: TEMPORAL_CERT_PEM
      remoteRef:
        key: {{ .Values.vault.secretBasePath }}/temporal-cert-pem
        property: TEMPORAL_CERT_PEM
    - secretKey: TEMPORAL_KEY_PEM
      remoteRef:
        key: {{ .Values.vault.secretBasePath }}/temporal-key-pem
        property: TEMPORAL_KEY_PEM
