apiVersion: v1
kind: Service
metadata:
  name: {{ include "terminus-watchdog.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "terminus-watchdog.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.health.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "terminus-watchdog.selectorLabels" . | nindent 4 }}
