{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "terminus-watchdog.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "terminus-watchdog.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "terminus-watchdog.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: metrics
      path: /metrics
      interval: {{ .Values.serviceMonitor.interval }}
{{- end }}
